# Generated by Django 5.2.8 on 2025-11-11 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReferencePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome do posto/entidade')),
                ('type', models.CharField(choices=[('UBS', 'UBS'), ('CRAS', 'CRAS'), ('ASSOCIACAO', 'Associação'), ('ONG', 'ONG'), ('OUTRO', 'Outro')], max_length=20, verbose_name='Tipo')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('neighborhood_coverage', models.CharField(blank=True, max_length=255, verbose_name='Bairros atendidos (texto livre)')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefone/WhatsApp')),
                ('contact_name', models.CharField(blank=True, max_length=100, verbose_name='Responsável')),
                ('opening_hours', models.CharField(blank=True, max_length=255, verbose_name='Dias/horários de atendimento')),
                ('can_receive_donations', models.BooleanField(default=False, verbose_name='Recebe doações neste local?')),
                ('public', models.BooleanField(default=True, verbose_name='Pode aparecer no site/app?')),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome completo')),
                ('whatsapp', models.CharField(max_length=50, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='Bairro')),
                ('allow_whatsapp', models.BooleanField(default=True, verbose_name='Autoriza contato por WhatsApp?')),
                ('preferred_kit', models.CharField(blank=True, choices=[('KIT_BASICO', 'Kit Básico'), ('KIT_BASICO_ALERGICA', 'Kit Básico Alérgica'), ('KIT_COMPLETO', 'Kit Completo'), ('KIT_COMPLETO_ALERGICA', 'Kit Completo Alérgica')], max_length=40, verbose_name='Tipo de kit que deseja doar')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reference_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.referencepost', verbose_name='Posto de referência do bairro')),
            ],
            options={
                'verbose_name': 'Doadora',
                'verbose_name_plural': 'Doadoras',
            },
        ),
    ]
