# Generated by Django 5.2.8 on 2026-01-07 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('whatsapp', models.CharField(max_length=20, verbose_name='WhatsApp')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='Bairro')),
                ('preferred_kit', models.CharField(choices=[('basic', 'Básico'), ('basic_allergy', 'Básico Alérgica'), ('complete', 'Completo'), ('complete_allergy', 'Completo Alérgica')], max_length=30, verbose_name='Tipo de kit')),
                ('allow_whatsapp', models.BooleanField(default=True, verbose_name='Aceita contato via WhatsApp')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReferencePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome do posto')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('neighborhood_coverage', models.CharField(max_length=200, verbose_name='Bairros atendidos')),
                ('can_receive_donations', models.BooleanField(default=True)),
                ('public', models.BooleanField(default=True)),
                ('contact_name', models.CharField(max_length=100, verbose_name='Responsável')),
                ('contact_phone', models.CharField(max_length=30, verbose_name='Telefone')),
                ('type', models.CharField(choices=[('ubs', 'UBS'), ('cras', 'CRAS'), ('hospital', 'Hospital'), ('ong', 'ONG')], max_length=20, verbose_name='Tipo de posto')),
            ],
        ),
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('whatsapp', models.CharField(max_length=20, verbose_name='WhatsApp')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='Bairro')),
                ('needed_kit', models.CharField(choices=[('basic', 'Básico'), ('basic_allergy', 'Básico Alérgica'), ('complete', 'Completo'), ('complete_allergy', 'Completo Alérgica')], max_length=30, verbose_name='Tipo de kit necessário')),
                ('is_breast_cancer_patient', models.BooleanField(default=False, verbose_name='Paciente com câncer de mama')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reference_post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.referencepost', verbose_name='Posto de referência')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_code', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Código de retirada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_donor', to='core.donor')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_receiver', to='core.receiver')),
                ('reference_post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.referencepost', verbose_name='Posto de retirada')),
            ],
        ),
        migrations.AddField(
            model_name='donor',
            name='reference_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.referencepost', verbose_name='Posto de referência'),
        ),
    ]
