# Generated by Django 5.2.8 on 2025-11-12 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('whatsapp', models.CharField(max_length=50, verbose_name='WhatsApp')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='Bairro')),
                ('is_breast_cancer_patient', models.BooleanField(default=True, verbose_name='Pós-cirurgia / em tratamento de câncer de mama')),
                ('needed_kit', models.CharField(choices=[('KIT_BASICO', 'Kit Básico'), ('KIT_BASICO_ALERGICA', 'Kit Básico Alérgica'), ('KIT_COMPLETO', 'Kit Completo'), ('KIT_COMPLETO_ALERGICA', 'Kit Completo Alérgica')], max_length=40, verbose_name='Kit necessário')),
                ('notes', models.TextField(blank=True, verbose_name='Observações internas')),
                ('active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reference_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.referencepost', verbose_name='Posto de referência do bairro')),
            ],
            options={
                'verbose_name': 'Receptora',
                'verbose_name_plural': 'Receptoras',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kit_type', models.CharField(choices=[('KIT_BASICO', 'Kit Básico'), ('KIT_BASICO_ALERGICA', 'Kit Básico Alérgica'), ('KIT_COMPLETO', 'Kit Completo'), ('KIT_COMPLETO_ALERGICA', 'Kit Completo Alérgica')], max_length=40, verbose_name='Tipo de Kit')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADO', 'Confirmado'), ('ENTREGUE', 'Entregue'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, verbose_name='Observações internas')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.donor', verbose_name='Doadora')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.receiver', verbose_name='Receptora')),
            ],
            options={
                'verbose_name': 'Match (Doação)',
                'verbose_name_plural': 'Matches (Doações)',
            },
        ),
    ]
