# Generated by Django 5.2.8 on 2026-01-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='pickup_code',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Código de retirada'),
        ),
    ]
