# Generated by Django 5.2.8 on 2025-11-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_receiver_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='pickup_code',
            field=models.CharField(blank=True, max_length=10, unique=True, verbose_name='Código de retirada'),
        ),
        migrations.AddField(
            model_name='match',
            name='pickup_used',
            field=models.BooleanField(default=False, verbose_name='Código já utilizado?'),
        ),
        migrations.AddField(
            model_name='match',
            name='pickup_used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/hora da retirada'),
        ),
    ]
