# Generated by Django 5.2.8 on 2026-01-07 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_match_pickup_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='notified',
            field=models.BooleanField(default=False, verbose_name='Notificação enviada'),
        ),
        migrations.AddField(
            model_name='match',
            name='notified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da notificação'),
        ),
        migrations.AlterField(
            model_name='match',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Retirada realizada'),
        ),
    ]
