# Generated by Django 6.0 on 2026-01-19 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_match_notified_match_notified_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='allow_whatsapp',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='city',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='preferred_kit',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='reference_post',
        ),
        migrations.RemoveField(
            model_name='match',
            name='notified',
        ),
        migrations.RemoveField(
            model_name='match',
            name='notified_at',
        ),
        migrations.AddField(
            model_name='donor',
            name='kit_type',
            field=models.CharField(choices=[('BASICO', 'Kit Básico'), ('ALERGIA', 'Kit Alergia')], default='BASICO', max_length=30, verbose_name='Tipo de kit doado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.donor', verbose_name='Doador'),
        ),
        migrations.AlterField(
            model_name='match',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Entrega concluída'),
        ),
        migrations.AlterField(
            model_name='match',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.receiver', verbose_name='Receptora'),
        ),
        migrations.AlterField(
            model_name='receiver',
            name='needed_kit',
            field=models.CharField(choices=[('BASICO', 'Kit Básico'), ('ALERGIA', 'Kit Alergia')], max_length=30, verbose_name='Tipo de kit necessário'),
        ),
    ]
